---
name: "Prepare macports-ports CI environment"

on:
  push:
    branches:
      - travis-ci
    tags:
      - v*

jobs:
  build:
    name: "Prepare macports-ports CI environment"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 64
      - name: Cleanup /usr/local
        run: |
          sudo mkdir /opt/local.old
          sudo mv /usr/local/* /opt/local.old
      - name: Build MacPorts Base
        run: |
          set -eu
          ./configure
          make
          sudo make install
          make test
      - name: Prepare Deployment
        run: |
          set -eu

          sed -i "" "s/-v selfupdate/version/" portmgr/dmg/postflight
          sudo install -d -m755 /opt/local/libexec/macports/postflight
          sudo install -m755 \
            portmgr/dmg/postflight \
            /opt/local/libexec/macports/postflight/
          sudo install -m644 \
            src/*.tcl \
            /opt/local/libexec/macports/postflight/
          tar cjf "MacPorts.tar.bz2" /opt/local
      - name: Deploy to bintray
        run: |
          set -eu

          # printf is a built-in, so this won't show up in ps(1)
          printf \
            "machine api.bintray.com\n\tlogin %s\n\tpassword %s\n" \
            "$user" \
            "$pass" > ~/.netrc
          chmod 600 ~/.netrc

          os_major=$(uname -r | cut -f 1 -d .)
          macports_version=$(cat config/macports_version)
          sha256=$(openssl dgst -sha256 -binary "MacPorts.tar.bz2" \
              | xxd -ps -c256)
          curl \
            --upload-file "MacPorts.tar.bz2" \
            --netrc \
            --header "X-Checksum-Sha2: ${sha256}" \
            --header "X-Bintray-Package: MacPorts" \
            --header "X-Bintray-Version: ${macports_version}" \
            --header "X-Bintray-Publish: 1" \
            --header "X-Bintray-Override: 1" \
            "https://api.bintray.com/content/macports-ci-env/macports-base/MacPorts-${os_major}.tar.bz2"
        env:
          user: "macports-ci-env"
          pass: ${{ secrets.BINTRAY_API_TOKEN }}
